### ISSUE TITLE
Progress output on put, post and get

### ISSUE THREAD

**Issue by l00mi** [zazuko/barnard59-graph-store#17]
We have many pipelines which take quite some time on the final uploading. During the time of the upload there is no feedback on the status. Is it possible to provide a progress output, or at least a absolut output in how many triples / bytes are already sent?

**Comment by bergos** [comment]
We don't have any standard solution to forward progress to the logging. I see this more like a debug feature than logging, cause it will be mainly used on troublemaker endpoints. Flooding the logs is therefore not the solution. That's why I think it makes most sense to use [debug](https://www.npmjs.com/package/debug) and send a message every 1000 quads. That would require to set the `DEBUG` environment variable to `DEBUG=barnard59-graph-store` to enable the output. What that be OK for you?

**Comment by l00mi** [comment]
From vshn: Would it be possible to log the current transfer speed node-fetch is getting (or total number of bytes transferred), maybe every 5 seconds?

**Comment by l00mi** [comment]
https://www.npmjs.com/package/node-fetch-progress

**Comment by bergos** [comment]
Will be implemented as described here: https://github.com/zazuko/barnard59/issues/121
