### ISSUE TITLE
Unhandled promise rejection on invalid endpoint setup

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59-graph-store#6]
The graph store steps are not resilient to misconfiguration, for example:

* endpoint URL without protocol
* using https instead of http
* invalid credentials

## Current behavior

When something is incorrect about the graph store settings the pipeline drops an "unhandled rejection" message in the standard output and the process continues.

## Expected behavior

The pipeline should immediately stop and the error should be handled by barnard59

**Comment by bergos** [comment]
The operations have now better error handling and the pipeline will stop processing after an error showed up.

Here is a list of uses cases + error messages tested in the latest version:

- endpoint URL without protocol: *Only HTTP(S) protocols are supported*
- using https instead of http: *request to https://localhost:3030/test/data failed, reason: write EPROTO 140345875068736:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:*
- invalid credentials: *Unauthorized*
- unknown host: *request to http://localhost1:3030/test/data failed, reason: getaddrinfo ENOTFOUND localhost1 localhost1:3030*
